# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DictionaryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DictionaryApp
pod 'Alamofire', '~> 4.4' 

  target 'DictionaryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DictionaryAppUITests' do
    # Pods for testing
  end

end
