# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactsAppD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactsAppD
pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'ContactsAppDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactsAppDUITests' do
    # Pods for testing
  end

end
